from enum import Enum

class StrEnum(str, Enum):
    pass


class RevisionStatus(StrEnum):
    DRAFT = "DRAFT"
    REVIEW_REQUESTED = "REVIEW_REQUESTED"
    APPROVED = "APPROVED"
    SUPERSEDED = "SUPERSEDED"
    REJECTED = "REJECTED"
    DEPRECATED = "DEPRECATED"


class Priority(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class AssertionKind(StrEnum):
    USER_CONFIRMED = "USER_CONFIRMED"
    APPROVED_DECISION = "APPROVED_DECISION"
    SOURCE_QUOTED = "SOURCE_QUOTED"
    AI_INFERENCE = "AI_INFERENCE"
    ASSUMPTION = "ASSUMPTION"


class ArtifactType(StrEnum):
    CHAPTER = "CHAPTER"
    FRD = "FRD"
    NFRD = "NFRD"
    HLD = "HLD"
    LLD = "LLD"
    VERIFICATION = "VERIFICATION"
    IMPLEMENTATION = "IMPLEMENTATION"


class ConstraintType(StrEnum):
    QUALITY = "QUALITY"
    BUSINESS = "BUSINESS"
    SCOPE = "SCOPE"
    TECHNOLOGY = "TECHNOLOGY"
    INTEGRATION = "INTEGRATION"
    DATA_GOVERNANCE = "DATA_GOVERNANCE"
    COMPLIANCE = "COMPLIANCE"
    DELIVERY = "DELIVERY"
    ARCHITECTURE = "ARCHITECTURE"


class QualityCategory(StrEnum):
    PERFORMANCE = "PERFORMANCE"
    AVAILABILITY = "AVAILABILITY"
    RELIABILITY = "RELIABILITY"
    SECURITY = "SECURITY"
    PRIVACY = "PRIVACY"
    ACCESSIBILITY = "ACCESSIBILITY"
    OBSERVABILITY = "OBSERVABILITY"
    USABILITY = "USABILITY"


class ExecutionMode(StrEnum):
    AUTOMATED = "AUTOMATED"
    MANUAL = "MANUAL"
    MIXED = "MIXED"


class AssessmentStage(StrEnum):
    DESIGN = "DESIGN"
    PRE_RELEASE = "PRE_RELEASE"
    RUNTIME = "RUNTIME"
    PERIODIC = "PERIODIC"
    VERIFICATION = "VERIFICATION"


class EvidenceType(StrEnum):
    TEST_RUN = "TEST_RUN"
    AUDIT_REPORT = "AUDIT_REPORT"
    CONFIGURATION_SNAPSHOT = "CONFIGURATION_SNAPSHOT"
    REVIEW_RECORD = "REVIEW_RECORD"
    BENCHMARK = "BENCHMARK"
    TEST_RESULT = "TEST_RESULT"


class EdgeType(StrEnum):
    CONTAINS = "CONTAINS"
    HAS_ACCEPTANCE = "HAS_ACCEPTANCE"
    APPLIES_TO = "APPLIES_TO"
    ASSESSED_BY = "ASSESSED_BY"
    CONSTRAINS = "CONSTRAINS"
    SELECTS = "SELECTS"
    IMPLEMENTS = "IMPLEMENTS"
    EXPOSES = "EXPOSES"
    REALIZES = "REALIZES"
    SPECIFIED_BY = "SPECIFIED_BY"
    VERIFIED_BY = "VERIFIED_BY"
    VERIFIES = "VERIFIES"
    EXECUTED_AS = "EXECUTED_AS"
    PRODUCED = "PRODUCED"
    CONFIRMS = "CONFIRMS"
    IMPLEMENTATION_OF = "IMPLEMENTATION_OF"
    SUPERSEDES = "SUPERSEDES"
    PROVENANCE_OF = "PROVENANCE_OF"


class EdgeBasis(StrEnum):
    EXPLICIT = "EXPLICIT"
    DERIVED = "DERIVED"
    INFERRED = "INFERRED"
    
class ActorType(StrEnum):
    USER = "USER"
    SYSTEM = "SYSTEM"
    AGENT = "AGENT"
    LLM = "LLM"
    TOOL = "TOOL"


class ApprovalDecision(StrEnum):
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class GovernanceOperation(StrEnum):
    CREATE = "CREATE"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    APPROVE = "APPROVE"
    REJECT = "REJECT"
    SUPERSEDE = "SUPERSEDE"