"""initial schema

Revision ID: b873531d4fbe
Revises: 
Create Date: 2026-10-07 11:30:53.011849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b873531d4fbe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=255), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('revision_id', sa.String(length=255), nullable=False),
    sa.Column('record_version', sa.String(length=100), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_approvals_record_id'), 'approvals', ['record_id'], unique=False)
    op.create_index(op.f('ix_approvals_revision_id'), 'approvals', ['revision_id'], unique=False)
    op.create_index('ix_approvals_revision_timestamp', 'approvals', ['revision_id', 'timestamp'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('governed_records',
    sa.Column('revision_id', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('assertion_kind', sa.String(length=100), nullable=False),
    sa.Column('record_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_governed_records_entity_id'), 'governed_records', ['entity_id'], unique=False)
    op.create_index('ix_governed_records_entity_version', 'governed_records', ['entity_id', 'version'], unique=False)
    op.create_table('graph_nodes',
    sa.Column('revision_id', sa.String(length=255), nullable=False),
    sa.Column('entity_id', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('assertion_kind', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_index(op.f('ix_graph_nodes_entity_id'), 'graph_nodes', ['entity_id'], unique=False)
    op.create_index('ix_graph_nodes_entity_version', 'graph_nodes', ['entity_id', 'version'], unique=False)
    op.create_table('provenance_events',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('revision_id', sa.String(length=255), nullable=False),
    sa.Column('record_version', sa.String(length=100), nullable=False),
    sa.Column('previous_revision_id', sa.String(length=255), nullable=True),
    sa.Column('previous_version', sa.String(length=100), nullable=True),
    sa.Column('payload_hash', sa.String(length=128), nullable=False),
    sa.Column('approval_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_provenance_events_actor', 'provenance_events', ['actor'], unique=False)
    op.create_index(op.f('ix_provenance_events_approval_id'), 'provenance_events', ['approval_id'], unique=False)
    op.create_index(op.f('ix_provenance_events_record_id'), 'provenance_events', ['record_id'], unique=False)
    op.create_index('ix_provenance_events_record_timestamp', 'provenance_events', ['record_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_provenance_events_revision_id'), 'provenance_events', ['revision_id'], unique=False)
    op.create_table('document_memberships',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('record_entity_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_memberships_document', 'document_memberships', ['document_id'], unique=False)
    op.create_index('ix_document_memberships_document_record', 'document_memberships', ['document_id', 'record_entity_id'], unique=True)
    op.create_index('ix_document_memberships_record', 'document_memberships', ['record_entity_id'], unique=False)
    op.create_table('document_revisions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('document_id', sa.String(length=255), nullable=False),
    sa.Column('baseline_id', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_revisions_baseline', 'document_revisions', ['baseline_id'], unique=False)
    op.create_index('ix_document_revisions_document', 'document_revisions', ['document_id'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('source_revision_id', sa.String(length=255), nullable=False),
    sa.Column('target_revision_id', sa.String(length=255), nullable=False),
    sa.Column('edge_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('basis', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_revision_id'], ['graph_nodes.revision_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_revision_id'], ['graph_nodes.revision_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_graph_edges_source', 'graph_edges', ['source_revision_id'], unique=False)
    op.create_index('ix_graph_edges_target', 'graph_edges', ['target_revision_id'], unique=False)
    op.create_index('ix_graph_edges_type', 'graph_edges', ['edge_type'], unique=False)
    op.create_table('document_locations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('document_revision_id', sa.String(length=255), nullable=False),
    sa.Column('record_revision_id', sa.String(length=255), nullable=False),
    sa.Column('anchor', sa.String(length=500), nullable=False),
    sa.Column('line_start', sa.Integer(), nullable=False),
    sa.Column('line_end', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_revision_id'], ['document_revisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_locations_document_record', 'document_locations', ['document_revision_id', 'record_revision_id'], unique=True)
    op.create_index('ix_document_locations_document_revision', 'document_locations', ['document_revision_id'], unique=False)
    op.create_index('ix_document_locations_record_revision', 'document_locations', ['record_revision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_locations_record_revision', table_name='document_locations')
    op.drop_index('ix_document_locations_document_revision', table_name='document_locations')
    op.drop_index('ix_document_locations_document_record', table_name='document_locations')
    op.drop_table('document_locations')
    op.drop_index('ix_graph_edges_type', table_name='graph_edges')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_document_revisions_document', table_name='document_revisions')
    op.drop_index('ix_document_revisions_baseline', table_name='document_revisions')
    op.drop_table('document_revisions')
    op.drop_index('ix_document_memberships_record', table_name='document_memberships')
    op.drop_index('ix_document_memberships_document_record', table_name='document_memberships')
    op.drop_index('ix_document_memberships_document', table_name='document_memberships')
    op.drop_table('document_memberships')
    op.drop_index(op.f('ix_provenance_events_revision_id'), table_name='provenance_events')
    op.drop_index('ix_provenance_events_record_timestamp', table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_record_id'), table_name='provenance_events')
    op.drop_index(op.f('ix_provenance_events_approval_id'), table_name='provenance_events')
    op.drop_index('ix_provenance_events_actor', table_name='provenance_events')
    op.drop_table('provenance_events')
    op.drop_index('ix_graph_nodes_entity_version', table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_entity_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index('ix_governed_records_entity_version', table_name='governed_records')
    op.drop_index(op.f('ix_governed_records_entity_id'), table_name='governed_records')
    op.drop_table('governed_records')
    op.drop_table('documents')
    op.drop_index('ix_approvals_revision_timestamp', table_name='approvals')
    op.drop_index(op.f('ix_approvals_revision_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_record_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
