from __future__ import annotations

from datetime import datetime, timezone
from uuid import uuid4

from app.database.repositories.provenance_event_repository import (
    ProvenanceEventRepository,
)
from app.models.graph.enums import (
    ActorType,
    GovernanceOperation,
    GovernanceSubjectType,
)
from app.models.graph.provenance_event import ProvenanceEvent
from app.models.graph.records import Record
from app.utils.hashing import sha256_canonical


class ProvenanceEventService:
    """
    Application service for product-owned governance audit events.

    Audit events are generated by aigov rather than supplied by callers.
    """

    def __init__(
        self,
        repository: ProvenanceEventRepository,
    ) -> None:
        self._repository = repository

    def record(
        self,
        *,
        record: Record,
        actor: str,
        actor_type: ActorType,
        operation: GovernanceOperation,
        previous_record: Record | None = None,
        approval_id: str | None = None,
    ) -> ProvenanceEvent:
        previous_revision_id = (
            previous_record.meta.revision_id
            if previous_record is not None
            else None
        )

        previous_version = (
            previous_record.meta.version
            if previous_record is not None
            else None
        )

        event = ProvenanceEvent(
            event_id=self._generate_event_id(),
            actor=actor,
            actor_type=actor_type,
            operation=operation,
            timestamp=datetime.now(timezone.utc),
            subject_type=GovernanceSubjectType.RECORD_REVISION,
            subject_id=record.meta.entity_id,
            revision_id=record.meta.revision_id,
            record_version=record.meta.version,
            previous_revision_id=previous_revision_id,
            previous_version=previous_version,
            payload_hash=sha256_canonical(record),
            approval_id=approval_id,
        )

        self._repository.append(event)

        return event

    def get(
        self,
        event_id: str,
    ) -> ProvenanceEvent | None:
        return self._repository.get(event_id)

    def list_for_record(
        self,
        record_id: str,
    ) -> list[ProvenanceEvent]:
        return self._repository.list_for_record(
            record_id
        )

    def list_all(
        self,
    ) -> list[ProvenanceEvent]:
        return self._repository.list_all()

    @staticmethod
    def _generate_event_id() -> str:
        return f"EVT-{uuid4().hex}"